/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API Index
         * @description Returns API information and available endpoints
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API Index Information */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiIndex"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Returns the health status of the API
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Health Check Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthCheck"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apiClient": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get API Client
         * @description Returns the generated API client with TypeScript types and usage examples
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API Client Information */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiClientResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiClientError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}

export interface components {
  schemas: {
    // Common/API meta
    ApiIndex: any;
    HealthCheck: any;
    ApiClientResponse: any;
    ApiClientError: any;

    // Auth
    SignUpRequest: any;
    AuthResponse: any; // used in authResponseToSessionResponse
    ErrorResponse: any;
    SignInRequest: any;
    SignOutResponse: any;
    EmailVerificationRequest: any;
    EmailVerificationResponse: any;

    // Profile
    ProfileResponse: any;
    UpdateProfileRequest: any;
    UpdateProfileResponse: any;
    ProfilePreferences: any;

    // Files
    File: any;
    UploadFileRequest: any;
    UploadFileResponse: any;
    GetFileResponse: any;
    DeleteResponse: any;

    // Listings
    ListingResponse: any;
    ListingListResponse: any;
    SingleListingResponse: any;
    CreateListingRequest: any;
    UpdateListingRequest: any;
    SaveDraftListingRequest: any;
    BulkCreateResponse: any;

    // Organization / Members
    Organization: any;
    UpdateOrganizationRequest: any;
    MembersListResponse: any;
    InviteMemberRequest: any;
    UpdateMemberRoleRequest: any;
    AcceptInvitationRequest: any;
    SuccessResponse: any;
    InvitationsListResponse: any;
    Invitation: any;
    Member: any; // used in MembersList UI

    // Reports
    QuarterlyReportRequest: any;
    ListingReportRequest: any;
  };
}
